#listing shortening services
shortening_services =r"\bbit\.ly\b|\bgoo\.gl\b|\bshorte\.st\b|\bgo2l\.ink\b|\bx\.co\b|\bow\.ly\b|\bt\.co\b|\btr\.im\b|\bis\.gd\b|\bcli\.gs\b|" \
r"\byfrog\.com\b|\bmigre\.me\b|\bff\.im\b|\btiny\.cc\b|\burl4\.eu\b|\btwit\.ac\b|\bsu\.pr\b|\btwurl\.nl\b|\bsnipurl\.com\b|" \
r"\bshort\.to\b|\bping\.fm\b|\bpost\.ly\b|\bjust\.as\b|\bbkite\.com\b|\bsnipr\.com\b|\bfic\.kr\b|\bloopt\.us\b|" \
r"\bdoiop\.com\b|\bshort\.ie\b|\bkl\.am\b|\bwp\.me\b|\brubyurl\.com\b|\bom\.ly\b|\bto\.ly\b|\bbit\.do\b|\blnkd\.in\b|\bdb\.tt\b|" \
r"\bqr\.ae\b|\badf\.ly\b|\bbitly\.com\b|\bcur\.lv\b|\btinyurl\.com\b|\bow\.ly\b|\bbit\.ly\b|\bity\.im\b|\bq\.gs\b|\bpo\.st\b|\bbc\.vc\b|\btwitthis\.com\b|\bu\.to\b|\bj\.mp\b|\bbuzurl\.com\b|\bcutt\.us\b|\bu\.bb\b|\byourls\.org\b|" \
r"\bprettylinkpro\.com\b|\bscrnch\.me\b|\bfiloops\.info\b|\bvzturl\.com\b|\bqr\.net\b|\btweez\.me\b|\bv\.gd\b|\blink\.net\b|\bsnurl\.com\b|\bus\.to\b|" \
r"\b0rz\.tw\b|" \
r"\b1-url\.net\b|" \
r"\b126\.am\b|" \
r"\b1tk\.us\b|" \
r"\b1un\.fr\b|" \
r"\b1url\.com\b|" \
r"\b1url\.cz\b|" \
r"\b1wb2\.net\b|" \
r"\b2\.gp\b|" \
r"\b2\.ht\b|" \
r"\b2ad\.in\b|" \
r"\b2doc\.net\b|" \
r"\b2fear\.com\b|" \
r"\b2tu\.us\b|" \
r"\b2ty\.in\b|" \
r"\b2u\.xf\.cz\b|" \
r"\b3ra\.be\b|" \
r"\b3x\.si\b|" \
r"\b4i\.ae\b|" \
r"\b4ks\.net\b|" \
r"\b4view\.me\b|" \
r"\b5em\.cz\b|" \
r"\b5url\.net\b|" \
r"\b5z8\.info\b|" \
r"\b6fr\.ru\b|" \
r"\b6g6\.eu\b|" \
r"\b7\.ly\b|" \
r"\b76\.gd\b|" \
r"\b77\.ai\b|" \
r"\b7fth\.cc\b|" \
r"\b7li\.in\b|" \
r"\b7vd\.cn\b|" \
r"\b8u\.cz\b|" \
r"\b944\.la\b|" \
r"\b98\.to\b|" \
r"\bL9\.fr\b|" \
r"\bLvvk\.com\b|" \
r"\bTo8\.cc\b|" \
r"\ba0\.fr\b|" \
r"\babbr\.sk\b|" \
r"\bad-med\.cz\b|" \
r"\bad5\.eu\b|" \
r"\bad7\.biz\b|" \
r"\badb\.ug\b|" \
r"\badfa\.st\b|" \
r"\badfly\.fr\b|" \
r"\badli\.pw\b|" \
r"\badv\.li\b|" \
r"\bajn\.me\b|" \
r"\baka\.gr\b|" \
r"\balil\.in\b|" \
r"\bamzn\.to\b|" \
r"\bany\.gs\b|" \
r"\baqva\.pl\b|" \
r"\bares\.tl\b|" \
r"\basso\.in\b|" \
r"\bau\.ms\b|" \
r"\bayt\.fr\b|" \
r"\bazali\.fr\b|" \
r"\bb00\.fr\b|" \
r"\bb23\.ru\b|" \
r"\bb54\.in\b|" \
r"\bbaid\.us\b|" \
r"\bbeam\.to\b|" \
r"\bbee4\.biz\b|" \
r"\bbim\.im\b|" \
r"\bbitw\.in\b|" \
r"\bblap\.net\b|" \
r"\bble\.pl\b|" \
r"\bblip\.tv\b|" \
r"\bboi\.re\b|" \
r"\bbote\.me\b|" \
r"\bbougn\.at\b|" \
r"\bbr4\.in\b|" \
r"\bbrk\.to\b|" \
r"\bbrzu\.net\b|" \
r"\bbul\.lu\b|" \
r"\bbxl\.me\b|" \
r"\bbzh\.me\b|" \
r"\bcachor\.ro\b|" \
r"\bcaptur\.in\b|" \
r"\bcashfly\.com\b|" \
r"\bcbs\.so\b|" \
r"\bcbug\.cc\b|" \
r"\bcc\.cc\b|" \
r"\bccj\.im\b|" \
r"\bcf\.ly\b|" \
r"\bcf2\.me\b|" \
r"\bcf6\.co\b|" \
r"\bchilp\.it\b|" \
r"\bcjb\.net\b|" \
r"\bclikk\.in\b|" \
r"\bclk\.im\b|" \
r"\bcn86\.org\b|" \
r"\bcouic\.fr\b|" \
r"\bcr\.tl\b|" \
r"\bcudder\.it\b|" \
r"\bcurl\.im\b|" \
r"\bcurte\.me\b|" \
r"\bcut\.pe\b|" \
r"\bcut\.sk\b|" \
r"\bcutt\.eu\b|" \
r"\bcutu\.me\b|" \
r"\bcybr\.fr\b|" \
r"\bcyonix\.to\b|" \
r"\bd75\.eu\b|" \
r"\bdaa\.pl\b|" \
r"\bdai\.ly\b|" \
r"\bdecenturl\.com\b|" \
r"\bdd\.ma\b|" \
r"\bddp\.net\b|" \
r"\bdft\.ba\b|" \
r"\bdigbig\.com\b|" \
r"\bdolp\.cc\b|" \
r"\bdopice\.sk\b|" \
r"\bdroid\.ws\b|" \
r"\bdv\.gd\b|" \
r"\bdyo\.gs\b|" \
r"\be37\.eu\b|" \
r"\beasyurl\.net\b|" \
r"\becra\.se\b|" \
r"\bely\.re\b|" \
r"\bencurtador\.com\.br\b|" \
r"\berax\.cz\b|" \
r"\berw\.cz\b|" \
r"\besy\.es\b|" \
r"\bex9\.co\b|" \
r"\bezurl\.cc\b|" \
r"\bfff\.re\b|" \
r"\bfff\.to\b|" \
r"\bfff\.wf\b|" \
r"\bfilz\.fr\b|" \
r"\bfnk\.es\b|" \
r"\bfoe\.hn\b|" \
r"\bfolu\.me\b|" \
r"\bfreze\.it\b|" \
r"\bfur\.ly\b|" \
r"\bfwdurl\.net\b|" \
r"\bg00\.me\b|" \
r"\bgca\.sh\b|" \
r"\bgg\.gg\b|" \
r"\bgoo\.lu\b|" \
r"\bgrem\.io\b|" \
r"\bguiama\.is\b|" \
r"\bhadej\.co\b|" \
r"\bhide\.my\b|" \
r"\bhjkl\.fr\b|" \
r"\bhops\.me\b|" \
r"\bhref\.li\b|" \
r"\bht\.ly\b|" \
r"\bi-2\.co\b|" \
r"\bi99\.cz\b|" \
r"\bicit\.fr\b|" \
r"\bick\.li\b|" \
r"\bicks\.ro\b|" \
r"\biiiii\.in\b|" \
r"\biky\.fr\b|" \
r"\bilix\.in\b|" \
r"\binfo\.ms\b|" \
r"\bisra\.li\b|" \
r"\bitm\.im\b|" \
r"\bix\.sk\b|" \
r"\bj\.gs\b|" \
r"\bjdem\.cz\b|" \
r"\bjieb\.be\b|" \
r"\bjp22\.net\b|" \
r"\bjqw\.de\b|" \
r"\bkask\.us\b|" \
r"\bkd2\.org\b|" \
r"\bkfd\.pl\b|" \
r"\bkorta\.nu\b|" \
r"\bkr3w\.de\b|" \
r"\bkrat\.si\b|" \
r"\bkratsi\.cz\b|" \
r"\bkrod\.cz\b|" \
r"\bkuc\.cz\b|" \
r"\bkxb\.me\b|" \
r"\bl-k\.be\b|" \
r"\blc-s\.co\b|" \
r"\blc\.cx\b|" \
r"\blcut\.in\b|" \
r"\bletop10\.\b|" \
r"\blibero\.it\b|" \
r"\blick\.my\b|" \
r"\blien\.li\b|" \
r"\blien\.pl\b|" \
r"\blin\.io\b|" \
r"\blinkn\.co\b|" \
r"\blinkbucks\.com\b|" \
r"\bllu\.ch\b|" \
r"\blnk\.co\b|" \
r"\blnk\.ly\b|" \
r"\blnk\.sk\b|" \
r"\blnks\.fr\b|" \
r"\blnky\.fr\b|" \
r"\blnp\.sn\b|" \
r"\blp25\.fr\b|" \
r"\bm1p\.fr\b|" \
r"\bm3mi\.com\b|" \
r"\bmake\.my\b|" \
r"\bmcaf\.ee\b|" \
r"\bmdl29\.net\b|" \
r"\bmic\.fr\b|" \
r"\bminu\.me\b|" \
r"\bmoourl\.com\b|" \
r"\bmore\.sh\b|" \
r"\bmut\.lu\b|" \
r"\bmyurl\.in\b|" \
r"\bnet\.ms\b|" \
r"\bnet46\.net\b|" \
r"\bnicou\.ch\b|" \
r"\bnig\.gr\b|" \
r"\bnotlong\.com\b|" \
r"\bnov\.io\b|" \
r"\bnq\.st\b|" \
r"\bnutshellurl\.com\b|" \
r"\bnxy\.in\b|" \
r"\bo-x\.fr\b|" \
r"\bokok\.fr\b|" \
r"\bonl\.li\b|" \
r"\bou\.af\b|" \
r"\bou\.gd\b|" \
r"\boua\.be\b|" \
r"\bouo\.io\b|" \
r"\bp\.pw\b|" \
r"\bparky\.tv\b|" \
r"\bpast\.is\b|" \
r"\bpdh\.co\b|" \
r"\bph\.ly\b|" \
r"\bpich\.in\b|" \
r"\bpin\.st\b|" \
r"\bplots\.fr\b|" \
r"\bplots\.fr\b|" \
r"\bpm\.wu\.cz\b|" \
r"\bppfr\.it\b|" \
r"\bppst\.me\b|" \
r"\bppt\.cc\b|" \
r"\bppt\.li\b|" \
r"\bpqn\.bz\b|" \
r"\bprejit\.cz\b|" \
r"\bptab\.it\b|" \
r"\bptm\.ro\b|" \
r"\bpw2\.ro\b|" \
r"\bpy6\.ru\b|" \
r"\bqbn\.ru\b|" \
r"\bqqc\.co\b|" \
r"\bqrtag\.fr\b|" \
r"\bqxp\.cz\b|" \
r"\bqxp\.sk\b|" \
r"\br\.cont\.us\b|" \
r"\brb6\.co\b|" \
r"\brcknr\.io\b|" \
r"\brdz\.me\b|" \
r"\bredir\.ec\b|" \
r"\bredir\.fr\b|" \
r"\bredu\.it\b|" \
r"\bref\.so\b|" \
r"\breise\.lc\b|" \
r"\brelink\.fr\b|" \
r"\brepla\.cr\b|" \
r"\bri\.ms\b|" \
r"\briz\.cz\b|" \
r"\brod\.gs\b|" \
r"\broflc\.at\b|" \
r"\brt\.se\b|" \
r"\bs-url\.fr\b|" \
r"\bsafe\.mn\b|" \
r"\bsagyap\.tk\b|" \
r"\bsdu\.sk\b|" \
r"\bseeme\.at\b|" \
r"\bsegue\.se\b|" \
r"\bsh\.st\b|" \
r"\bsh\.st\b|" \
r"\bshar\.as\b|" \
r"\bshrinkurl\.us\b|" \
r"\bshorl\.com\b|" \
r"\bshort\.cc\b|" \
r"\bshort\.pk\b|" \
r"\bshrt\.in\b|" \
r"\bshy\.si\b|" \
r"\bsmu\.sh\b|" \
r"\bsicax\.net\b|" \
r"\bsina\.lt\b|" \
r"\bsk\.gy\b|" \
r"\bskr\.sk\b|" \
r"\bskroc\.pl\b|" \
r"\bsmll\.co\b|" \
r"\bsn\.im\b|" \
r"\bsnsw\.us\b|" \
r"\bsoo\.gd\b|" \
r"\bsort3\.me\b|" \
r"\bspn\.sr\b|" \
r"\bsq6\.ru\b|" \
r"\bssl\.gs\b|" \
r"\bsurl\.me\b|" \
r"\bsux\.cz\b|" \
r"\bsy\.pe\b|" \
r"\bt\.cn\b|" \
r"\bta\.gd\b|" \
r"\btabzi\.com\b|" \
r"\btau\.pe\b|" \
r"\btdjt\.cz\b|" \
r"\bthesa\.us\b|" \
r"\btighturl\.com\b|" \
r"\btin\.li\b|" \
r"\btini\.cc\b|" \
r"\btiny\.lt\b|" \
r"\btiny\.ms\b|" \
r"\btiny\.pl\b|" \
r"\btinyurl\.hu\b|" \
r"\btixsu\.com\b|" \
r"\btldr\.sk\b|" \
r"\btllg\.net\b|" \
r"\btnij\.org\b|" \
r"\btny\.cz\b|" \
r"\btohle\.de\b|" \
r"\btpmr\.com\b|" \
r"\btr5\.in\b|" \
r"\btrck\.me\b|" \
r"\btrick\.ly\b|" \
r"\btrkr\.ws\b|" \
r"\btrunc\.it\b|" \
r"\btwet\.fr\b|" \
r"\btwi\.im\b|" \
r"\btwlr\.me\b|" \
r"\buby\.es\b|" \
r"\bucam\.me\b|" \
r"\bug\.cz\b|" \
r"\bulmt\.in\b|" \
r"\bunlc\.us\b|" \
r"\bupzat\.com\b|" \
r"\bur1\.ca\b|" \
r"\burl2\.fr\b|" \
r"\burl5\.org\b|" \
r"\burl\.ie\b|" \
r"\burl\.likedeck\.com\b|" \
r"\burl\.lotpatrol\.com\b|" \
r"\burlcut\.com\b|" \
r"\burlin\.it\b|" \
r"\burls\.fr\b|" \
r"\burltea\.com\b|" \
r"\burlz\.fr\b|" \
r"\burub\.us\b|" \
r"\butfg\.sk\b|" \
r"\bv\.ht\b|" \
r"\bv5\.gd\b|" \
r"\bvaaa\.fr\b|" \
r"\bvalv\.im\b|" \
r"\bvaza\.me\b|" \
r"\bvbly\.us\b|" \
r"\bvd55\.com\b|" \
r"\bverd\.in\b|" \
r"\bvgn\.me\b|" \
r"\bvov\.li\b|" \
r"\bvsll\.eu\b|" \
r"\bvt802\.us\b|" \
r"\bvur\.me\b|" \
r"\bvv\.vg\b|" \
r"\bw1p\.fr\b|" \
r"\bwaa\.ai\b|" \
r"\bwapurl\.co\.uk\b|" \
r"\bwb1\.eu\b|" \
r"\bweb99\.eu\b|" \
r"\bwed\.li\b|" \
r"\bwideo\.fr\b|" \
r"\bwtc\.la\b|" \
r"\bwu\.cz\b|" \
r"\bww7\.fr\b|" \
r"\bwwy\.me\b|" \
r"\bx\.nu\b|" \
r"\bx10\.mx\b|" \
r"\bx2c\.eu\b|" \
r"\bx2c\.eumx\b|" \
r"\bxav\.cc\b|" \
r"\bxgd\.in\b|" \
r"\bxib\.me\b|" \
r"\bxl8\.eu\b|" \
r"\bxoe\.cz\b|" \
r"\bxrl\.us\b|" \
r"\bxt3\.me\b|" \
r"\bxua\.me\b|" \
r"\bxub\.me\b|" \
r"\bxurls\.co\b|" \
r"\byagoa\.fr\b|" \
r"\byagoa\.me\b|" \
r"\byatuc\.com\b|" \
r"\byau\.sh\b|" \
r"\byeca\.eu\b|" \
r"\byect\.com\b|" \
r"\byep\.it\b|" \
r"\byogh\.me\b|" \
r"\byon\.ir\b|" \
r"\byoufap\.me\b|" \
r"\byoutu\.be\b|" \
r"\bysear\.ch\b|" \
r"\byyv\.co\b|" \
r"\bz9\.fr\b|" \
r"\bzSMS\.net\b|" \
r"\bzapit\.nu\b|" \
r"\bzeek\.ir\b|" \
r"\bzip\.net\b|" \
r"\bzkr\.cz\b|" \
r"\bzkrat\.me\b|" \
r"\bzkrt\.cz\b|" \
r"\bzoodl\.com\b|" \
r"\bzpag\.es\b|" \
r"\bzti\.me\b|" \
r"\bzxq\.net\b|" \
r"\bzyva\.org\b|" \
r"\bzzb\.bz\b"